import type { AtoManifest } from "../types/ato";

const DEFAULT_PERMISSIONS: AtoManifest["permissions"] = [
  "chat",
  "suggest:actions",
];

const DEFAULT_MEMORY_POLICY: AtoManifest["memoryPolicy"] = "session";
const DEFAULT_SAFETY_PROFILE: AtoManifest["safetyProfile"] = "standard";
const ACTIVE_STATUS: AtoManifest["status"] = "active";

export const REQUIRED_OFFICIAL_ATO_MANIFEST_IDS = ["namc-reader"] as const;

export const OFFICIAL_ATO_MANIFESTS: AtoManifest[] = [
  {
    id: "brooks-ai-hub",
    displayName: "Brooks AI HUB",
    slashPath: "Brooks AI HUB",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "brooksbears",
    displayName: "BrooksBears",
    slashPath: "BrooksBears",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "brooksbears-benjamin-bear",
    displayName: "Benjamin Bear",
    slashPath: "BrooksBears/BenjaminBear",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "founders",
    status: ACTIVE_STATUS,
  },
  {
    id: "mycarmindato",
    displayName: "MyCarMindATO",
    slashPath: "MyCarMindATO",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "mycarmindato-driver",
    displayName: "MyCarMindATO - Driver",
    slashPath: "MyCarMindATO/Driver",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
    badge: "free",
  },
  {
    id: "mycarmindato-trucker",
    displayName: "MyCarMindATO - Trucker",
    slashPath: "MyCarMindATO/Trucker",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "founders",
    status: ACTIVE_STATUS,
  },
  {
    id: "mycarmindato-delivery-driver",
    displayName: "MyCarMindATO - Delivery Driver",
    slashPath: "MyCarMindATO/DeliveryDriver",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
    badge: "free",
  },
  {
    id: "mycarmindato-traveler",
    displayName: "MyCarMindATO - Traveler",
    slashPath: "MyCarMindATO/Traveler",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
    badge: "free",
  },
  {
    id: "myflowerai",
    displayName: "MyFlowerAI",
    slashPath: "MyFlowerAI",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "brooks-ai-hub-summaries",
    displayName: "Brooks AI HUB Summaries",
    slashPath: "Brooks AI HUB/Summaries",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "founders",
    status: ACTIVE_STATUS,
  },
  {
    id: "nat",
    displayName: "Northern Americana Tech Agent",
    slashPath: "NAT",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "namc",
    displayName: "NAMC AI Media Curator",
    slashPath: "NAMC",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
  },
  {
    id: "namc-reader",
    displayName: "NAMC Reader",
    slashPath: "NAMC/Reader",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "founders",
    status: ACTIVE_STATUS,
  },
  {
    id: "spotify-music-player",
    displayName: "Spotify Music Player",
    slashPath: "Spotify",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
    badge: "free",
  },
  {
    id: "namc-lore-playground",
    displayName: "Lore Playground",
    slashPath: "NAMC/Lore-Playground",
    permissions: DEFAULT_PERMISSIONS,
    memoryPolicy: DEFAULT_MEMORY_POLICY,
    safetyProfile: DEFAULT_SAFETY_PROFILE,
    entitlementRequirements: "none",
    status: ACTIVE_STATUS,
    badge: "free",
  },
];
