export const DM_RECIPIENT_LIMIT_DEFAULT = 4;
export const DM_RECIPIENT_LIMIT_FOUNDER = 12;

export const PRIVATE_MEMBER_LIMIT_DEFAULT = DM_RECIPIENT_LIMIT_DEFAULT + 1;
export const PRIVATE_MEMBER_LIMIT_FOUNDER_HOST = DM_RECIPIENT_LIMIT_FOUNDER + 1;
